### ISSUE TITLE
swagger测试tag时，无法调用任何结构，参入参数无法解析，是否是注释问题？

### ISSUE THREAD

**Issue by minibear2333** [golang-minibear2333/gin-blog#3]
http://localhost:8000/swagger/index.html

**Comment by LVM-23** [comment]
\app\form.go  里面对应接口入参封装 使用的是err := c.ShouldBind(v) ，这个的对应 表单提交类型，所以解析不了swagger提交的json对象类型，需要改成 err := c.ShouldBindJSON(v)，就可以了。 还有一部，就是封装入参的对象得加个对json解析的映射，例如json:"name"，

type CreateTagRequest struct {
	Name      string `form:"name" json:"name" binding:"required,min=2,max=100"`
	CreatedBy string `form:"created_by" json:"created_by"   binding:"required,min=2,max=100"`
	State     uint8  `form:"state,default=1" json:"state"   binding:"oneof=0 1"`
}

**Comment by LVM-23** [comment]
1、\app\form.go 里面对应接口入参封装 使用的是err := c.ShouldBind(v) ，这个的对应 表单提交类型，解析不了swagger提交的json对象类型，需要改成 err := c.ShouldBindJSON(v)，就可以了。 

2、就是封装入参的对象得加个对json解析的映射，例如json:"name"，
例：
type CreateTagRequest struct {
Name string form:"name" json:"name" binding:"required,min=2,max=100"
CreatedBy string form:"created_by" json:"created_by" binding:"required,min=2,max=100"
State uint8 form:"state,default=1" json:"state" binding:"oneof=0 1"
}

3、swagger注释修改，  internal\routers\api\v1\tag.go

例如： 
// @Summary 新增标签
// @Produce  json
// @Accept  json
// @Param data body service.CreateTagRequest true "数据封装"  
// @Success 200 {object} model.Tag "成功"
// @Failure 400 {object} errcode.Error "请求错误"
// @Failure 500 {object} errcode.Error "内部错误"
// @Router /api/v1/tags [post]
func (t Tag) Create(c *gin.Context) { .......


还好是写得比较多java 接口，对swager还算熟悉，看着原接口每个参数都标有in body,觉得怪怪的，然后最后一个参数的内容覆盖前面的参数在请求体里面只有最后一个参数值，发现了问题。

跟着熊哥学go
